name: Some workflow

on:
  workflow_dispatch:
    inputs:
      some-input:
        description: 'Some input'
        required: true
        type: choice
        options:
          - 'option1'
          - 'option2'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tests
        run: echo "tests"