name: Some workflow

on:
#  workflow_dispatch:
#    inputs:
#      some-input:
#        description: 'Some input'
#        required: true
#        type: choice
#        options:
#          - 'option1'
#          - 'option2'
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tests
        run: echo "tests"
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tests
        run: echo "tests"
  sonar:
    name: Sonarqube
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tests
        run: echo "tests"
  image:
    name: Build Image
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tests
        run: echo "tests"
  envuat:
    name: Deploy UAT
    needs: image
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echouat
        run: echo "uat env"
  envdev:
    name: Deploy DEV
    needs: image
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echodev
        run: echo "devenv"
